api/urls.py
# -*- coding: utf-8 -*-
####
#   Project:      unimap
#   Applicattion: api
####
from django.contrib import admin
from django.urls import include, path
from django.views.decorators.csrf import csrf_exempt
from djgeojson.views import GeoJSONLayerView
from unimap.models import Toilet, Hotel, Zone, Route, PointData

from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from api import views

urlpatterns = [
    #path('', include(router.urls)),

    # Toilet PointData
    path('v1/toilet.geojson', views.toiletdata, name="toilet"),
    #path('v1/toilet.geojson',GeoJSONLayerView.as_view(
    #    model=Toilet,
    #    properties=['Name','Summery','Floor','Babyseat','Ostomate','Nursingbed','Washlet','Rotation','Emergencycall',
    #                'Photo1','Photo2','Photo360']
    #), name='toilet'),

    # Hotel PointData
    path('v1/hotel.geojson', views.hoteldata, name="hotel"),
    #path('v1/hotel.geojson',GeoJSONLayerView.as_view(
    #    model=Hotel,
    #    properties=['Name','Summery','TEL','Address','Access','URL','URL_f21',
    #                'Photo1','Photo2','Photo3','Photo360','Photo360_2']
    #), name='hotel'),
    
    # Pass ZoneData
    path('v1/zone.geojson', views.zonedata, name="zone"),
    #path('v1/zone.geojson',GeoJSONLayerView.as_view(
    #   model=Zone,
    #    properties=['Name','Summery','Sort', 'Photo1','Photo2','Photo3','Photo360','Photo360_2']
    #), name='zone'),

    # Course Route :LineString
    path('v1/route.geojson',GeoJSONLayerView.as_view(
        model=Route,
        properties=['AreaId','Sort','Name','Summery']
    ), name='route'),

    # Course Route bu AreaId
    path('v1/route/<int:areaid>', views.route, name='route'),
    
    # Course PointData
    path('v1/point.geojson', views.pointdata, name="pointdata"),
    #path('v1/point.geojson',GeoJSONLayerView.as_view(
    #model=PointData,
    #    properties=['AreaId','Sort','No','Name','Summery','Remarks','Open','Close','OpeningNote',
    #                'Holiday','Price','PriceNote','Discount','TEL','URL','Urltitle',
    #                'Photo1','Photo2','Photo3','Photo360','Photo360_2']
    #), name='point'),
    
    # Course Route by AreaId
    path('v1/point/<int:areaid>', views.routepointdata, name='pointdata'),
]

unimap/urls.py
# -*- coding: utf-8 -*-
####
#   Unimap Project
####
"""
The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings           # add
from django.conf.urls.static import static # add

from unimap import views

admin.site.site_header='奈良ユニバーサル観光マップ管理画面'
admin.site.site_title='奈良ユニバーサル観光マップ管理画面'
admin.site.index_title='ホーム'


urlpatterns = [
    # 管理ページ
    path('admin/', admin.site.urls),

    # rest-API
    path('api/', include('api.urls')),
    
    # トップページ
    path('', views.toppage, name='toppage'),

    # コース一覧ページ
    path('area', views.arealist, name='arealist'),

    # テストページ
    path('test', views.test, name='test'),

    # エリアマップ
    path('map', views.map, name='map'),
    path('map/<int:areaid>', views.map, name='map'),

    # ホテル詳細
    path('hotel/<int:hotelid>', views.hotel, name='hotel'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static('photo/', document_root=settings.MEDIA_ROOT)
urlpatterns += static('photos/', document_root=settings.MEDIA_ROOT+"/photos")
urlpatterns += static('akalstabimage/', document_root=settings.MEDIA_ROOT+"/akalstabimage")

unimap/models.py
# -*- coding: utf-8 -*-
####
#   Unimap Project models.py     
####
from django.contrib.auth import get_user_model

#from django.db import models
from django.contrib.gis.db import models as models
from django.contrib.gis.geos import Point, LineString

#FileValidator
from django.core.validators import FileExtensionValidator

import os
    
# 推奨コース
class Area(models.Model):
    AreaType_CHOICES = ( ( 1, 'エリア'),( 2, 'コース') )

    id       = models.AutoField(primary_key=True)
    AreaSort = models.IntegerField(verbose_name="マップタイプ",choices=AreaType_CHOICES, default=1 )
    DisplayOrder = models.IntegerField(verbose_name="表示順",null=True,blank=True)
    DisplayFlag  = models.BooleanField(verbose_name="表示ON/OFF",default=False)
    Name     = models.CharField(verbose_name="エリア名",max_length=24)
    SubName  = models.CharField(verbose_name="サブタイトル",max_length=24)
    Abstruct = models.TextField(verbose_name="概要",max_length=256)
    Booklet  = models.CharField(verbose_name="収録冊子",max_length=24,null=True,blank=True)
    DEF_LAT  = models.FloatField(verbose_name="中心緯度",default=34.6)
    DEF_LON  = models.FloatField(verbose_name="中心経度",default=135.8)
    DEF_Zoom = models.IntegerField(verbose_name="ズームレベル",default=15 )
    Timestamp= models.DateTimeField(verbose_name="更新日時",blank=True, null=True, auto_now=True)
    
    def __str__(self):
        return self.Name

    class Meta:
        verbose_name = '1.マップエリア'
        verbose_name_plural = '1.マップエリア'

# イラスト地図
class ImageMap(models.Model):
    id       = models.AutoField(primary_key=True)
    AreaId   = models.ForeignKey('Area', to_field='id', on_delete=models.PROTECT, verbose_name="エリアID")
    ImageMap = models.ImageField(verbose_name="イラスト地図",upload_to="images/",null=True)
    LAT1     = models.FloatField(verbose_name="左上緯度")
    LON1     = models.FloatField(verbose_name="左上経度")
    LAT2     = models.FloatField(verbose_name="右下緯度")
    LON2     = models.FloatField(verbose_name="右下経度")
    Timestamp= models.DateTimeField(verbose_name="更新日時", blank=True, null=True, auto_now=True)

    #def __str__(self):
    #    return self.AreaId

    class Meta:
        verbose_name = '2.イラストマップ'
        verbose_name_plural = '2.イラストマップ'
    # See https://qiita.com/kojionilk/items/da20c732642ee7377a78
    
# 移動ルート
class Route(models.Model):
    SortType_CHOICES = ( ( 1, 'メインコース'),( 2, 'オプション'), ( 11, 'ゆるい坂'),( 12, '中くらいの坂'),( 13, '急な坂') )
    id       = models.AutoField(primary_key=True)
    AreaId   = models.ForeignKey('Area', to_field='id', on_delete=models.PROTECT, verbose_name="エリアID", default=1)
    Sort     = models.IntegerField(verbose_name="ルート種類",choices=SortType_CHOICES, default=1 )
    Name     = models.CharField(verbose_name="名称",max_length=24,null=False)
    Summery  = models.CharField(verbose_name="概要",max_length=256,null=True,blank=True)
    geom     = models.LineStringField(verbose_name="ルート座標",srid=4326,default=LineString( [135.82, 34.681],[135.83, 34.685]) )
    Timestamp= models.DateTimeField(verbose_name="更新日時",blank=True, null=True, auto_now=True)

    def _get_linestring(self):
        "Returns a linestring"
        return '%s' % ( self.geom)
    LineString = property(_get_linestring)
    
    def __str__(self):
        return self.Name
    class Meta:
        verbose_name = '3.推奨ルート'
        verbose_name_plural = '3.推奨ルート'

# 地点
class PointData(models.Model):
    PointType_CHOICES = ( ( 1, 'route'), (12, 'option' ),
                          ( 2, 'start'), ( 3, 'end'), ( 4, 'start_op'), ( 5, 'end_op'),
                          ( 7, 'barrguide'), ( 14, 'roadguide'),
                          ( 8, 'attention'), ( 9, 'caution'),
                          ( 6, 'location'), (10, 'busstop'),
                          (11, 'shop' ) ,  (13,'restaurant') 
                         )

    id        = models.AutoField(primary_key=True)
    AreaId    = models.ForeignKey('Area', to_field='id', on_delete=models.PROTECT, verbose_name="エリアID", default=1)
    Sort      = models.IntegerField(verbose_name="地点タイプ",choices=PointType_CHOICES, default=1 )
    No        = models.IntegerField(verbose_name="地点番号",null=True,blank=True)
    Name      = models.CharField(verbose_name="エリア名",max_length=24,null=False)
    Summery   = models.CharField(verbose_name="概要",max_length=256,null=True,blank=True)
    Remarks   = models.CharField(verbose_name="備考",max_length=256,null=True,blank=True)
    Open      = models.CharField(verbose_name="開始時刻",max_length=256,null=False,blank=True)
    Close     = models.CharField(verbose_name="終了時刻",max_length=256,null=False,blank=True)
    OpeningNote= models.CharField(verbose_name="時刻注釈",max_length=256,null=False,blank=True)
    Holiday   = models.CharField(verbose_name="休日",max_length=256,null=False,blank=True)
    Price     = models.CharField(verbose_name="価格",max_length=256,null=False,blank=True)
    PriceNote = models.CharField(verbose_name="価格注釈",max_length=256,null=False,blank=True)
    Discount  = models.CharField(verbose_name="割引",max_length=256,null=False,blank=True)
    TEL       = models.CharField(verbose_name="電話番号",max_length=16,null=False,blank=True)
    URL       = models.CharField(verbose_name="URL",max_length=256,null=False,blank=True)
    Urltitle  = models.CharField(verbose_name="URL名称",max_length=24,null=False,blank=True)
    Image1    = models.ImageField(verbose_name="画像１",upload_to="photos/point/",null=True,blank=True)
    Image2    = models.ImageField(verbose_name="画像２",upload_to="photos/point/",null=True,blank=True)
    Photo1    = models.CharField(verbose_name="Photo1",max_length=256,null=True,blank=True)
    Photo2    = models.CharField(verbose_name="Photo2",max_length=256,null=True,blank=True)
    Photo360  = models.CharField(verbose_name="Photo360",max_length=256,null=True,blank=True)
    geom      = models.PointField(srid=4326,default=Point([135.82, 34.68]))
    Timestamp = models.DateTimeField(verbose_name="更新日時",blank=True, null=True, auto_now=True)
    objects   = models.Manager()
    
    def __str__(self):
        return self.Name

    class Meta:
        verbose_name = '4.ルート上の地点'
        verbose_name_plural = '4.ルート上の地点'

# ゾーン
class Zone(models.Model):
    SortType_CHOICES = ( ( 1, 'gravel'),( 2, 'difficulty'),( 3, 'impassable'),( 4, 'traffic') )

    id       = models.AutoField(primary_key=True)
    AreaId    = models.ForeignKey('Area', to_field='id', on_delete=models.PROTECT, verbose_name="エリアID", default=1 )
    Sort      = models.IntegerField(verbose_name="ゾーンタイプ",choices=SortType_CHOICES, default=1 )
    Name      = models.CharField(verbose_name="名称",max_length=24,null=False)
    Summery   = models.CharField(verbose_name="概要",max_length=256,null=True)
    Image1    = models.ImageField(verbose_name="画像１",upload_to="photos/zone/",null=True,blank=True)
    Image2    = models.ImageField(verbose_name="画像２",upload_to="photos/zone/",null=True,blank=True)
    Photo1    = models.CharField(verbose_name="Photo1",max_length=256,null=True,blank=True)
    Photo2    = models.CharField(verbose_name="Photo2",max_length=256,null=True,blank=True)
    Photo360  = models.CharField(verbose_name="Photo360",max_length=256,null=True,blank=True)
    geom      = models.PolygonField(srid=4326)
    Timestamp= models.DateTimeField(verbose_name="更新日時",blank=True, null=True, auto_now=True)

    def __str__(self):
        return self.Name
    class Meta:
        verbose_name = 'A.ゾーン情報'
        verbose_name_plural = 'A.ゾーン情報'

## WIP try Proxy
#class ZoneProxy(Zone):
#    class Meta:
#        proxy = True


# トイレ
class Toilet(models.Model):
    SortType_CHOICES = ( ( 100, 'toilet'),( 999, 'etc') )

    id       = models.AutoField(primary_key=True)
    AreaId    = models.ForeignKey('Area', to_field='id', on_delete=models.PROTECT, verbose_name="エリアID",null=True)
    Sort      = models.IntegerField(verbose_name="地点タイプ",choices=SortType_CHOICES, default=100 )
    Name      = models.CharField(verbose_name="名称",max_length=24,null=False)
    Summery   = models.CharField(verbose_name="概要",max_length=256,null=True,blank=True)
    Floor     = models.CharField(verbose_name="階数",max_length=24,null=True,blank=True)

    Babyseat  = models.BooleanField(verbose_name="ベビーシート",default=False)
    Ostomate  = models.BooleanField(verbose_name="オストメイト",default=False)
    Nursingbed= models.BooleanField(verbose_name="介護ベット",default=False)
    Washlet   = models.BooleanField(verbose_name="ウォシュレット",default=False)
    Rotation  = models.BooleanField(verbose_name="車いす転回",default=False)
    Emergencycall = models.BooleanField(verbose_name="呼出ボタン",default=False)

    Image1    = models.ImageField(verbose_name="画像１",upload_to="photos/toilet/",null=True,blank=True)
    Image2    = models.ImageField(verbose_name="画像２",upload_to="photos/toilet/",null=True,blank=True)
    Photo1    = models.CharField(verbose_name="Photo1",max_length=256,null=True,blank=True)
    Photo2    = models.CharField(verbose_name="Photo2",max_length=256,null=True,blank=True)
    Photo360  = models.CharField(verbose_name="Photo360",max_length=256,null=True,blank=True)
    geom      = models.PointField(srid=4326,default=Point([135.82, 34.68]))
    Timestamp = models.DateTimeField(verbose_name="更新日時",blank=True, null=True, auto_now=True)
    objects   = models.Manager()
    
    def __str__(self):
        return self.Name
    
    class Meta:
        verbose_name = 'B.トイレ情報'
        verbose_name_plural = 'B.トイレ情報'

# ホテル
class Hotel(models.Model):
    id       = models.AutoField(primary_key=True)
    AreaId    = models.ForeignKey('Area', to_field='id', on_delete=models.PROTECT, verbose_name="エリアID",null=True,blank=True)
    Name      = models.CharField(verbose_name="名称",max_length=24,null=False)
    Summery   = models.CharField(verbose_name="概要",max_length=256,null=True)
    TEL       = models.CharField(verbose_name="電話",max_length=24,null=False, default=0)
    Address   = models.CharField(verbose_name="住所",max_length=256,null=True,blank=True)
    

templates/area.html
{% extends "base.html" %}
{% block content %}

<script src="/static/js/area.js"></script>

<div class="mx-auto stdbl">
  <h1 align="center">コース一覧</h1>
</div>

<div class="mx-auto m-1" style="max-width: 800px;">
  <table class="table table-sm table-responsive" style="min-width=350px;" id="sorttable">
    <thead class="thead-light">
      <tr>
	<th scope="col" style="width: 30%" class="text-center align-middle">コース名称</th>
	<th scope="col" style="width: 30%" class="text-center align-middle">サブタイトル</th>
	<th scope="col" style="width: 40%" class="text-center align-middle">コース概要</th>
      </tr>
    </thead>
    <tbody id="arealist">
      {% for area in arealist %}
      <tr id="area-{{area.id}}">
	<td class="text-center">
	  <span class="d-inline-block text-truncate" style="max-width: 150px">
            <a href="{% url 'map' %}/{{ area.id }}">{{ area.Name }}</a>
	</span></td>
	<td class="text-center">
	  <span class="d-inline-block text-truncate" style="max-width: 150px">{{ area.SubName }}</span></td>
	<td class="text-center">
	  <span class="d-inline-block text-truncate" style="max-width: 400px">{{ area.Abstruct }}</span></td>
      </tr>
      {% endfor %}
    </tbody>    
    <caption class="text-center">コースリスト</caption>
  </table>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>オンライン版奈良ユニバーサル観光マップ|Nara Universal Map Online</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="icon" href="/static/favicon.ico">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/theme.bootstrap_4.min.css">
    <!-- Bootstrap/jquery js -->
    <script src="/static/js/jquery-3.5.1.slim.min.js"></script>
    <script src="/static/js/jquery.tablesorter.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- Leaflet -->
    <link rel="stylesheet" href="/static/css/leaflet.css" />
    <link rel="stylesheet" href="/static/css/unimap.css" />

    <!-- local ico -- 
    <link rel="icon" href="/static/favicon.ico"> -->
    <!-- local css --
    <link rel="stylesheet" href="/static/css/iotview.css"> -->
    <meta name="keywords" content="車椅子,障碍者,地図,奈良公園,東大寺,大仏,高畑,奈良町,ならまち,北町,きたまち,唐招提寺,薬師寺,石舞台,万葉文化館">
    <meta name="description" content="車いす使用者の方などを対象に、奈良観光を安全に楽しんでいただけるよう障がい者自身が調査し、バリアフリー情報を重視した観光マップです。">

  </head>
  <body>
    <div class="container">
      <div class="row mx-auto stdblk">
	<div class="bg-secondary text-white text-center p-2", style="width: 100%;">NeoUnimap</div>
      </div>
      {% if messages %}
      <div class="mx-auto text-center stdblk">
	<dl>
          {% for message in messages %}
          <dt>{{message}}</dt>
          {% endfor %}
	</dl>
      </div>
      {% endif %}

      {% block content %}
      {% endblock %}
      
      <hr class="mx-auto m-0" style="width: 100%">
      
      <div class="row mx-auto stdblk">
	<div class="text-right p-1", style="width: 100%;">
	  <a href="/admin" class="btn btn-outline-secondary text-black-50 btn-sm m-1" role="button">管理画面</a>
	</div>
      </div>
    </div>
  </body>
</html>

templates/course.html
{% extends "base.html" %}
{% block content %}

<script src="/static/js/course.js"></script>

<div class="mx-auto stdbl">
  <h1 align="center">コース一覧</h1>
</div>

<div class="mx-auto m-1" style="max-width: 800px;">
  <table class="table table-sm table-responsive" style="min-width=350px;" id="sorttable">
    <thead class="thead-light">
      <tr>
	<th scope="col" style="width: 30%" class="text-center align-middle">コース名称</th>
	<th scope="col" style="width: 30%" class="text-center align-middle">サブタイトル</th>
	<th scope="col" style="width: 40%" class="text-center align-middle">コース概要</th>
      </tr>
    </thead>
    <tbody id="courselist">
      {% for course in courselist %}
      <tr id="course-{{course.id}}">
	<td class="text-center">
	  <span class="d-inline-block text-truncate" style="max-width: 150px">{{ course.CourseName }}</span></td>
	<td class="text-center">
	  <span class="d-inline-block text-truncate" style="max-width: 150px">{{ course.CourseSubName }}</span></td>
	<td class="text-center">
	  <span class="d-inline-block text-truncate" style="max-width: 400px">{{ course.CourseAbstruct }}</span></td>
      </tr>
      {% endfor %}
    </tbody>    
    <caption class="text-center">コースリスト</caption>
  </table>
</div>

{% endblock %}

templates/ga.html
<!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ GOOGLE_ANALYTICS_ID }}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', '{{ GOOGLE_ANALYTICS_ID }}');
    </script>

templates/map.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>{{area.Name}}エリア by 奈良ユニバーサル観光マップ</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="icon" href="/static/favicon.ico">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Bootstrap/jquery js -->
    <!-- 
    <script src="/static/js/bootstrap.min.js"></script> -->
    <!-- Bootstrap CSS -->
    <!--
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/theme.bootstrap_4.min.css">
    -->
    <!-- jquery js -->
    <script src="/static/js/jquery-3.5.1.min.js"></script>
    <script src="/static/js/jquery.tablesorter.min.js"></script>

    <!-- Leaflet CSS-->
    <link rel="stylesheet" href="/static/css/leaflet.css">

    <!-- Leaflet JS-->
    <script type="text/javascript" src="/static/js/leaflet/leaflet.js"></script>
    <script type="text/javascript" src="/static/js/leaflet/leaflet.ajax.min.js"></script>
    <script type="text/javascript" src="/static/js/leaflet/gpx.js"></script>
    <script type="text/javascript" src="/static/js/leaflet/leaflet-ant-path.js"></script>
    <script type="text/javascript" src="/static/js/leaflet/leaflet-polygon.fillPattern.js"></script>
    
    <!-- local ico -- 
    <link rel="icon" href="/static/favicon.ico"> -->
    <!-- local css -->
    <link rel="stylesheet" href="/static/css/unimap_view.css">
    <!-- GOOGLE ANALYTICS -->
    {% if GOOGLE_ANALYTICS_ID %}
      <!-- GOOGLE ANALYTICS -->
      {% include 'ga.html' %}
    {% endif %}
  </head>
  <body>
    <header>
      <!-- Fixed navbar -->
      <nav class="m-0 px-1 py-0 navbar navbar-expand-xxl navbar-light fixed-top bg-light">
	<div class="container-fluid">
	  <p class="fs-5 navbar-brand">
	    <a class="px-1 p-0 m-0" href="/"><img src="/static/favicon.ico" height="24px" width="24px" alt="オンライン版 奈良ユニバーサル観光マップ"></a>
	    {{area.Name}}{{area.get_AreaSort_display}}&nbsp;
	  </p>
	  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
	  </button>
	  <div class="mx-2 collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item active">
		<a class="nav-link" aria-current="page" href="{% url 'toppage' %}">トップページ</a></li>
	      {% for area in arealist %}
              <li class="mx-1 nav-item active">
		<a class="nav-link" aria-current="page" href="{% url 'map' %}/{{ area.id }}">{{ area.Name }}</a></li>
	      {% endfor %}
            </ul>
	  </div>
	</div>
      </nav>

      <!-- Fixed navbar -->
      <!-- Fixed navbar 
	  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
	  </button>
      -->
    </header>
    
    <!-- Begin page content -->
    <div id="map"></div>
  </body>

  <script type="text/javascript" src="/static/js/unimap_license.js"></script>
  <script type="text/javascript" src="/static/js/unimap_style.js"></script>
  <script type="text/javascript" src="/static/js/unimap_popup.js"></script>
  <script type="text/javascript" src="/static/js/unimap_icon.js"></script>
  <script type="text/javascript" src="/static/js/unimap.js"></script>

  <script>
    const mapimg = {};
    mapimg.id = "{{area.id}}" ;
    mapimg.deflat = "{{area.DEF_LAT}}" ;
    mapimg.deflon = "{{area.DEF_LON}}" ;
    mapimg.defzoom= "{{area.DEF_Zoom}}" ;
    mapimg.url = "{{mediaurl}}" + "{{imagemap.ImageMap}}" ;
    mapimg.lat1 = "{{imagemap.LAT1}}" ;
    mapimg.lon1 = "{{imagemap.LON1}}" ;
    mapimg.lat2 = "{{imagemap.LAT2}}" ;
    mapimg.lon2 = "{{imagemap.LON2}}" ;
    /*console.log( "MapPage Params: id: {{mapimg.id}}  zoom:{{mapimg.defzoom}}   ImageMap: {{image.ImageMap}}" )*/
    drawMap( mapimg )
  </script>
</html>